### ISSUE TITLE
Non fonctionnel

### ISSUE THREAD

**Issue by ghost** [geobar78/Myelectricaldata-Graphana-Dashboard#1]
Hello

J'ai testé ta dites méthode , soit je me suis planté quelque part soit un truc de zappé ....
![Capture d’écran 2022-12-27 094625](https://user-images.githubusercontent.com/103725660/209639342-f65acdf2-99a8-4c4d-8412-ba7498087f1b.png)

Ma config de my electra
`influxdb:
  enable: true
  hostname: a0d7b954-influxdb
  port: 8086
  token: XXXXX:XXXXXX
  org: "-"
  bucket: myelectricaldata/autogen
  asynchronous: "false"`

Mon influxDB
![Capture d’écran 2022-12-27 094837](https://user-images.githubusercontent.com/103725660/209639567-7184add1-a513-4d22-ba05-1834ccd2397a.png)

![Capture d’écran 2022-12-27 094926](https://user-images.githubusercontent.com/103725660/209639624-820367b2-84b3-4da2-b2a6-b82e3e1e0a05.png)

Grafana

![grafa](https://user-images.githubusercontent.com/103725660/209639738-fb32223c-5dcd-4fdb-b0af-5fe287f97e24.png)
![Capture d’écran 2022-12-27 095055](https://user-images.githubusercontent.com/103725660/209639903-87cf82b2-babd-49fa-899b-4d04a0ff016f.png)

**Comment by geobar78** [comment]
Salut, oui c'est ta database Influxdb qui n'a pas le même nom que moi soit "DATABASE" "RETENTION"
pour que cela fonctionne chez toi tu dois éditer chaque panel pour lui indiquer la bonne base soit "myelectricaldata" "autogen" pour toi. c'est un poil long. 

![image](https://user-images.githubusercontent.com/75928935/209819428-de21baa0-95c7-4adf-b7c1-5ed02148393b.png)

Le plus rapide je pense est de créer une nouvelle base influx "DATABASE" retention policy "RETENTION" 

![image](https://user-images.githubusercontent.com/75928935/209819805-fe2a550a-37b7-4e24-9d8a-f844458a4a0f.png)

et ensuite modifier ton config.yalm avec bucket: "DATABASE/RETENTION"

**Comment by geobar78** [comment]
j'ai modifié le readme j'espère que ça sera plus clair.

**Comment by geobar78** [comment]
@Sonic62 c'est bon tu as réussi ?

**Comment by ghost** [comment]
Hello

dsl , avec les fetes j'avais oublié 
je refais cela est te tien au courant

PS: Bonne année 2023

**Comment by ghost** [comment]
C'est bon j'ai reussi a tout modifié !

Ca marche

**Comment by geobar78** [comment]
Cool content que ça ai fonctionné. Bonne Année à toi aussi.
